---
- name: Guide Data ush
  hosts: localhost
  user: todd
  tasks:
     - name: Run mc2xml
       shell: /home/todd/./mc2xml -T mtxsound:todd1328

     - name: Copy XMLTV File
       synchronize:
       src: /home/todd/xmltv.xml
       dest: rsync://192.168.1.148/srv/samba/IPTV/EPG/xmltv.xml
