---
- name: Guide Data ush
  hosts: localhost

  user: todd
  tasks:
     - name: Run mc2xml
       shell: /home/todd/./runEPG

     - name: Copy XMLTV File
       synchronize:
       src: localhost:/home/todd/xmltv.xml
       dest: rsync://192.168.1.148/srv/samba/IPTV/EPG/xmltv.xml
